# Generated by Django 5.0.7 on 2025-04-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=100)),
                ('establishment_year', models.IntegerField(blank=True, null=True)),
                ('visit_duration_hours', models.FloatField(blank=True, null=True)),
                ('google_rating', models.FloatField(default=3.0)),
                ('entrance_fee', models.FloatField(blank=True, null=True)),
                ('airport_within_city', models.BooleanField(default=False)),
                ('weekly_off', models.CharField(blank=True, max_length=100, null=True)),
                ('significance', models.CharField(blank=True, max_length=255, null=True)),
                ('dslr_allowed', models.BooleanField(default=False)),
                ('review_count', models.FloatField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(blank=True, related_name='itineraries', to='iti.touristlocation')),
            ],
        ),
    ]
